when@dev:
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler
        
 web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/https://meziane1981.github.io/kaliticssym6'
        prefix: /_profiler
